
theme: jekyll-theme-leap-day
# theme: jekyll-theme-cayman

title: Workshop on Cross-Market Recommendation (XMRec)
description: 

google_analytics: UA-206094552-1

markdown: GFM

plugins:
- jekyll-menus
