
theme: jekyll-theme-leap-day
# theme: jekyll-theme-cayman

title: WSDM Cup on Cross-Market Recommendation (XMRec)
description: WSDM 2022

google_analytics: UA-206094552-1

markdown: kramdown

plugins:
- jekyll-menus
