
theme: jekyll-theme-leap-day
# theme: jekyll-theme-cayman

title: Cross-Market Recommendation Competition (XMRec)
description: WSDM 2022

google_analytics: UA-206094552-1

markdown: GFM

plugins:
- jekyll-menus
